# Generated by Django 4.0 on 2022-01-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
